---
abstract: "LESPEA's Dist::Zilla Configuration"
author:
  - 'Adam Lesperance <lespea@gmail.com>'
build_requires:
  Dist::Zilla::Plugin::Bootstrap::lib: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  File::ShareDir::Install: 0.03
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-LESPEA
no_index:
  directory:
    - inc
    - t
    - xt
    - utils
    - share
    - example
    - examples
  file:
    - README.html
requires:
  CPAN::Meta::YAML: 0
  Carp: 0
  Dist::Zilla: 4.300000
  Dist::Zilla::Plugin::ArchiveRelease: 0
  Dist::Zilla::Plugin::Authority: 0
  Dist::Zilla::Plugin::AutoMetaResources: 0
  Dist::Zilla::Plugin::AutoPrereqs: 0
  Dist::Zilla::Plugin::ConfirmRelease: 0
  Dist::Zilla::Plugin::ConsistentVersionTest: 0
  Dist::Zilla::Plugin::CopyFilesFromBuild: 0
  Dist::Zilla::Plugin::DualBuilders: 0
  Dist::Zilla::Plugin::EOLTests: 0
  Dist::Zilla::Plugin::ExecDir: 0
  Dist::Zilla::Plugin::ExtraTests: 0
  Dist::Zilla::Plugin::FakeRelease: 0
  Dist::Zilla::Plugin::GatherDir: 0
  Dist::Zilla::Plugin::HasVersionTests: 0
  Dist::Zilla::Plugin::InstallGuide: 0
  Dist::Zilla::Plugin::License: 0
  Dist::Zilla::Plugin::MakeMaker: 0
  Dist::Zilla::Plugin::Manifest: 0
  Dist::Zilla::Plugin::ManifestSkip: 0
  Dist::Zilla::Plugin::MetaConfig: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaNoIndex: 0
  Dist::Zilla::Plugin::MetaTests: 0
  Dist::Zilla::Plugin::MetaYAML: 0
  Dist::Zilla::Plugin::MinimumPerl: 0
  Dist::Zilla::Plugin::ModuleBuild: 0
  Dist::Zilla::Plugin::NextRelease: 0
  Dist::Zilla::Plugin::NoTabsTests: 0
  Dist::Zilla::Plugin::PkgVersion: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::PruneCruft: 0
  Dist::Zilla::Plugin::ReadmeAnyFromPod: 0
  Dist::Zilla::Plugin::ReportVersions::Tiny: 0
  Dist::Zilla::Plugin::ShareDir: 0
  Dist::Zilla::Plugin::SpellingCommonMistakesTests: 0
  Dist::Zilla::Plugin::Test::CPAN::Changes: 0.005
  Dist::Zilla::Plugin::Test::Compile: 1.112400
  Dist::Zilla::Plugin::Test::DistManifest: v2.0.1
  Dist::Zilla::Plugin::Test::MinimumVersion: v2.0.1
  Dist::Zilla::Plugin::Test::Perl::Critic: 2.112410
  Dist::Zilla::Plugin::Test::Portability: v2.0.1
  Dist::Zilla::Plugin::Test::Synopsis: v2.0.1
  Dist::Zilla::Plugin::TestRelease: 0
  Dist::Zilla::Plugin::UploadToCPAN: 0
  Dist::Zilla::Role::MintingProfile::ShareDir: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 2.0
  Perl::Critic: 1.118
  Perl::Critic::Bangs: 1.08
  Perl::Critic::Lax: 0
  Perl::Critic::Pulp: 0
  Perl::Critic::StricterSubs: 0
  Perl::Critic::Swift: 0
  Perl::MinimumVersion: 0
  Perl::OSType: 0
  Perl::PrereqScanner: 0
  Pod::Coverage::TrustPod: 0
  Pod::Elemental::Transformer::List: 0
  Pod::Spell: 0
  Pod::Weaver: 3.101632
  Pod::Weaver::Config::Assembler: 0
  Pod::Weaver::Section::Installation: 0
  Pod::Weaver::Section::SeeAlso: 0
  Pod::Weaver::Section::Support: 0
  Pod::Weaver::Section::WarrantyDisclaimer: 0
  Test::CPAN::Meta: 0
  Test::Perl::Critic: 0
  Test::Pod::Content: 0
  namespace::autoclean: 0
  perl: 5.010
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-Author-LESPEA
  homepage: http://search.cpan.org/dist/Dist-Zilla-PluginBundle-Author-LESPEA
  repository: git://github.com/lespea/dist-zilla-pluginbundle-author-lespea.git
version: 1.006000
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::LESPEA/@Filter/GatherDir'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Author::LESPEA/@Filter/CopyFilesFromBuild'
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::LESPEA/@Filter/UploadToCPAN'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: '@Author::LESPEA/@Filter/ArchiveRelease'
      version: 4.00
    -
      class: Dist::Zilla::Plugin::AutoMetaResources
      name: '@Author::LESPEA/@Filter/AutoMetaResources'
      version: 1.110050
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::LESPEA/@Filter/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::LESPEA/@Filter/PkgVersion'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Author::LESPEA/@Filter/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::LESPEA/@Filter/NextRelease'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::LESPEA/@Filter/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::LESPEA/@Filter/AutoPrereqs'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::LESPEA/@Filter/MetaConfig'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@Author::LESPEA/@Filter/Test::Compile'
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::ConsistentVersionTest
      name: '@Author::LESPEA/@Filter/ConsistentVersionTest'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::LESPEA/@Filter/Test::Perl::Critic'
      version: 2.112410
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@Author::LESPEA/@Filter/Test::DistManifest'
      version: 2.000002
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@Author::LESPEA/@Filter/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::LESPEA/@Filter/MetaTests'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::LESPEA/@Filter/Test::MinimumVersion'
      version: 2.000002
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@Author::LESPEA/@Filter/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::LESPEA/@Filter/PodCoverageTests'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::LESPEA/@Filter/PodSyntaxTests'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::LESPEA/@Filter/Test::CPAN::Changes'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::SpellingCommonMistakesTests
      name: '@Author::LESPEA/@Filter/SpellingCommonMistakesTests'
      version: 1.001000
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::LESPEA/@Filter/ExtraTests'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::LESPEA/@Filter/PruneCruft'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::LESPEA/@Filter/ManifestSkip'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::LESPEA/@Filter/ExecDir'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::LESPEA/@Filter/ShareDir'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Author::LESPEA/@Filter/ReportVersions::Tiny'
      version: 1.05
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Author::LESPEA/@Filter/ModuleBuild'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::LESPEA/@Filter/MakeMaker'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::DualBuilders
      name: '@Author::LESPEA/@Filter/DualBuilders'
      version: 1.001
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Author::LESPEA/@Filter/MetaNoIndex'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::LESPEA/@Filter/License'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Author::LESPEA/@Filter/InstallGuide'
      version: 1.200000
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::LESPEA/@Filter/MetaJSON'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::LESPEA/@Filter/MetaYAML'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::LESPEA/@Filter/html.build'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::LESPEA/@Filter/text.build'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::LESPEA/@Filter/pod.root'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::LESPEA/@Filter/Manifest'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::LESPEA/@Filter/TestRelease'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::LESPEA/@Filter/ConfirmRelease'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: Git::Check
      version: 1.122460
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: Commit_Changes
      version: 1.122460
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: Git::Tag
      version: 1.122460
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: Git::Push
      version: 1.122460
    -
      class: Dist::Zilla::Plugin::ModuleShareDirs
      name: ModuleShareDirs
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: build
          type: requires
      name: BuildRequires
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300021
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300021
x_authority: cpan:LESPEA
